OpenAEV-Platform/agent

- .circleci/config.yml
> [agent] Provide OpenBAS agent for x86_64 architecture (#12)

- installer/windows/agent-installer.ps1
* https://github.com/OpenBAS-Platform/agent/issues/19
> [agent] Check powershell version before install

- .circleci/config.yml
- Cargo.toml
- config/default.toml
- installer/linux/agent-installer.sh
- installer/macos/agent-installer.sh
- installer/windows/README.md
- installer/windows/agent-installer.nsi
- installer/windows/agent-installer.ps1
- installer/windows/agent-upgrade.ps1
- src/api/mod.rs
- src/config/settings.rs
- src/main.rs
- src/process/agent_job.rs
- src/process/keep_alive.rs
* Attributes added for the agent works with unsecured certificate (like self signed) and environment with proxy
* Openbas and implant are impacted so there are PR in their repositories too
* https://github.com/OpenBAS-Platform/openbas/issues/1218
* https://github.com/OpenBAS-Platform/openbas/issues/1508
* https://github.com/OpenBAS-Platform/agent/issues/17
> [agent] Add attributes for unsecured certificate and env with proxy (#1218)

- installer/linux/agent-upgrade.sh
- installer/macos/agent-upgrade.sh
* Add the attributes to the sh upgrade script for Linux and Macos
* https://github.com/OpenBAS-Platform/agent/issues/22
> [agent] Fix upgrade agent for Linux and Macos

- .circleci/config.yml
*
*
* https://github.com/OpenBAS-Platform/openbas/issues/1909 
*
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
> [tool] update circle for prerelease platform (#1909)

- installer/windows/agent-installer.ps1
- installer/windows/agent-upgrade.ps1
* Agent can't be installed on some Windows machine, add more conditions to manage it
* https://github.com/OpenBAS-Platform/openbas/issues/2076
> [agent] Fix install and upgrade for x86 arch

- .circleci/config.yml
*
*
* Close #33 
*
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
> [tool] fix installer creation for win x86_64 in circle (#33)

- src/api/manage_jobs.rs
- src/api/mod.rs
- src/api/register_agent.rs
- src/config/execution_details.rs
- src/config/mod.rs
- src/main.rs
- src/process/agent_job.rs
- src/process/keep_alive.rs
* Adapt OpenBAS agent for the next tasks related to the agents (multi traces, installation mode,...)
3 PR in 1, need PR from openbas (https://github.com/OpenBAS-Platform/openbas/pull/2162) and implant (https://github.com/OpenBAS-Platform/implant/pull/36) to test
> [agent] Adapt backend on new agent logic (part 2)

- installer/windows/agent-installer.ps1
* Fix the installation when the location is C:\Windows\System32
* Fix the installer not removed when the installation is slow
* Give installation details when the script is launched
* https://github.com/OpenBAS-Platform/agent/issues/24
Installation with Powershell < 7 can or can not work (different github issues created with different errors : [#1151](https://github.com/OpenBAS-Platform/openbas/issues/1151), [#1496](https://github.com/OpenBAS-Platform/openbas/issues/1496) ). I allow now to try to install the agent with any Powershell and inform the user to install the agent with Powershell 7 if any error is encountered. If it's OK, I will update the documentation. 
Explanation for the System32 bug : https://github.com/electron-userland/electron-builder/issues/7301
> [agent] Improve installation script for Windows

- src/process/agent_exec.rs
* Fire and forget thread to call `wait()` on the child process handle (reaping it on completion)
* Fix #50 
This was tested on Linux (not macos)
> [agent] start a fire-and-forget thread to reap child process (#50)

- .circleci/config.yml
- installer/linux/agent-installer-service-user.sh
- installer/linux/agent-installer-session-user.sh
- installer/linux/agent-installer.sh
- installer/linux/agent-upgrade-service-user.sh
- installer/linux/agent-upgrade-session-user.sh
- installer/linux/agent-upgrade.sh
* adding 4 new scripts installation and upgrade scripts for service user and session user agents
###Testing process
* Pull the issue/1860 branch and run your backend service on this branch
* For testing download the scripts (installer and upgrade) locally on the machin you want to run the agent on
*  Replace the different values ${OPENBAS_URL}/${OPENBAS_TOKEN}/${OPENBAS_UNSECURED_CERTIFICATE}"/${OPENBAS_WITH_PROXY}
* for the session installer script execute: `sh agent-installer-service-user.sh`
* for the session upgrade script execute: `sh agent-upgrade-service-user.sh`
* for the service installer: `sudo sh agent-installer-service-user.sh --user [user] --group  [group]`
* for the service upgrade: `sh agent-upgrade-service-user.sh `
* #1860
*
If this is a relatively large or complex …
> [agent] Adding service user and session user linux installer/upgrade scripts

- .circleci/config.yml
* Fix for Windows installer to make nsis
*
*
*
> [agent] Fix for Windows installer to make nsis

- installer/windows/agent-upgrade-service-user.ps1
- installer/windows/agent-upgrade-session-user.ps1
* Fix upgrade scripts for Windows
*
*
*
> [agent] Fix upgrade scripts for Windows

- installer/windows/agent-installer-session-user.nsi
* Fix powershell displayed for agent session user
* #1860
> [agent] Fix for Windows installer session 

- .circleci/config.yml
* Cleaning the cache before saving it
*
* Closes #2719
*
> Cleaning the cache before saving it

- src/api/register_agent.rs
* Filter out non-relevant / loopback IP addresses before reporting to the platform
* Closes #54
> [agent] Filter out non-relevant IP and MAC addresses

- .circleci/config.yml
* [ci] Removing rust version installed with chocolatey
*
*
*
> [ci] Removing rust version installed with chocolatey

- src/main.rs
* Add hook to get all error logs
> [agent] Add hook to get all error logs

- installer/linux/agent-installer-service-user.sh
- installer/linux/agent-installer-session-user.sh
- installer/linux/agent-installer.sh
- installer/linux/agent-upgrade-service-user.sh
- installer/linux/agent-upgrade-session-user.sh
- installer/linux/agent-upgrade.sh
* backport of fix to install agents on linux boxes with degraded systemd
* Closes #70
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
> [agent] Agent will install even if systemd is in degraded mode (#70)

- .circleci/config.yml
- installer/linux/agent-upgrade-session-user.sh
- installer/linux/agent-upgrade.sh
- installer/macos/agent-upgrade-session-user.sh
- installer/macos/agent-upgrade.sh
- installer/windows/agent-installer-service-user.nsi
- installer/windows/agent-installer-service-user.ps1
- installer/windows/agent-installer-session-user.nsi
- installer/windows/agent-installer-session-user.ps1
- installer/windows/agent-installer.nsi
- installer/windows/agent-installer.ps1
- installer/windows/agent-upgrade-session-user.ps1
- installer/windows/agent-upgrade.ps1
* Update the upgrade scripts to manage the transition between OpenBAS and OpenAEV renaming
* https://github.com/OpenAEV-Platform/openaev/issues/3706
> [agent] Rework upgrade scripts for renaming
